export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const users: {id: number, nome:string, idade: number}[] = [
  {
      id: 1,
      nome: 'Caio',
      idade: 17
  }, 
  {
    id: 2,
    nome: 'Davi',
    idade: 11
},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
