import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import "@/app/(public)/layout.module.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Page Init",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div id="logo">Logo</div>
          <nav>
            <ul>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/about'>Sobre</Link>
              </li>
              <li>
                <Link href='/contact'>Contato</Link>
              </li>
              <li>
                <Link href='/login'>Entrar</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
